### ISSUE TITLE
ranking of words needed.

### ISSUE THREAD

**Issue by Wheeler1711** [chw3k5/Wordler#1]
Helper currently displays the remaining words and the remaining letters with their number of occurrences. It seems like a natural next step to rank all of the words for likelihood to yield the most useful information. I think a way to assign a numerical likelihood value could be as such. For each letter position still available for guessing each letter has a likelihood i.e. for the word awake. one might see that the letter a occurs in the first position in 10 out of the 256 remaining words so a likelihood value of 10/256. Then for the second letter w only occurs in that position in 1/256 words. Say the third letter a is already guessed in the right location so no value is assigned. Then k is 5/256 and e is 52/256. Then the total numerical value for awake would be 10/256+1/256+5/256+52/256 = 68/256 (really don't need to divide by 256 since that will be the same for all words). You then repeat this calculation for all remaining words and then sort. This is the first way to assign likelihood that comes to mind but there might be a better way. There is some inherent weighting in this method toward getting information about position versus just information about the occurrence.

**Comment by chw3k5** [comment]
A added a simple ranking function, see AvailableWords.get_rank_value() in narrow.py. This only accounts for the remaining words and the unknow letters. It is not an optimal path. 
![image](https://user-images.githubusercontent.com/8564941/154356847-954418a9-a349-46bc-9a94-fd80b8503702.png)

**Comment by Wheeler1711** [comment]
This is very interesting. Doesn't seem to support my previous assumption that a word with three vowels would be best. I think the optimum path must be computing all possible outcomes for each word and then counting up the size of the remaining words for each outcome and then averaging over this size over all outcomes. Then ranking. Might be computationally expensive. I will try for guess 0 to see what happens.

**Comment by chw3k5** [comment]
This is an open question. Very difficult (for me).

**Comment by Wheeler1711** [comment]
![image](https://user-images.githubusercontent.com/21267453/154632313-02e335c7-394b-49d1-9064-40c9d51a47bf.png)
when minimizing the resultant remaining word list length given all outcomes. No human can play like this :)

**Comment by chw3k5** [comment]
We have a number of these tools that now also interface with the game in play.py.
