### ISSUE TITLE
more convenient input

### ISSUE THREAD

**Issue by Wheeler1711** [chw3k5/Wordler#3]
Would like to be able to input information easier than having a bunch of long questions asked of me. Consider something like. 

Enter your guess word:
great
Enter wordle color codes 
g for in the correct position (green)
y for in the word (yellow)
x for not in the word (grey)
example: xgxyy

rather unfortunate that grey and green both start with g...

**Comment by chw3k5** [comment]
I updated the interface. See the attached screenshot.
![image](https://user-images.githubusercontent.com/8564941/154356380-ca91376e-d3ec-4138-a45c-d53c70ea0962.png)

**Comment by Wheeler1711** [comment]
works great!
